#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Слишком долго и не всегда корректно работает, временно отключено;
# npm run build:prod
# npm run lint:ts
# npm run lint:scss
# npm run test:unit
# npm run sb:build
