#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Слишком долго и не всегда корректно работает, временно отключено;
# UPD: на самом-то деле необходимости в данном функционале нет, потому что подключен и настроен CI на данном проекте, и всё, что написано ниже выполняется в GH Actions;
# npm run build:prod
# npm run lint:ts
# npm run lint:scss
# npm run test:unit
# npm run sb:build
