name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      # - name: linting css
      #   run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run sb:build && npm run test:ui:ci
      # - name: ui test ok
      #   run: npm run test:ui:ok
      # - name: update reference
      #   run: npx loki update --reactUri="file:./storybook-static"
      # - name: screenshot testing
      #   run: npm run test:ui:ci
      # - name: screenshot testing
      #   run: npx loki --requireReference --reactUri file:./storybook-static
